import Foundation

enum InterfaceLanguage: String { case english = "en", chinese = "zh-Hans" }
enum Localization {
    static var preferences = UserDefaults.standard
    static var language: InterfaceLanguage {
        get { InterfaceLanguage(rawValue: preferences.string(forKey: "interfaceLanguage") ?? "en") ?? .english }
        set { preferences.set(newValue.rawValue, forKey: "interfaceLanguage") }
    }
    static func key(for text: String) -> String { english[text] != nil ? text : (english.first { $0.value == text }?.key ?? text) }
    static let english: [String: String] = [
        "表头列": "Column",
        "[公式]": "[Formula]",
        "[图片]": "[Image]",
        "↩ 完成   esc 取消": "↩ Done   esc Cancel",
        "下划线": "Underline",
        "下划线 ⌘U": "Underline ⌘U",
        "保存失败，内容仍保留在窗口中": "Could not save. Your text is still in the editor.",
        "全选": "Select All",
        "公式过大，请拆分成几行。": "This formula is too large. Split it into smaller formulas.",
        "关于随记": "About SwiftNote",
        "关闭窗口": "Close Window",
        "写点什么，或输入 /": "Write something, or type /",
        "切换待办状态": "Toggle Checklist",
        "列": "columns",
        "列数": "Columns",
        "删除": "Delete",
        "删除当前备忘录": "Delete this note",
        "删除线": "Strikethrough",
        "删除这一行": "Delete Row",
        "删除这条备忘录？": "Delete this note?",
        "剪切": "Cut",
        "取消": "Cancel",
        "图片": "Image",
        "图片宽度": "Image width",
        "在下方插入一行": "Insert Row Below",
        "备忘录": "Note",
        "复制": "Copy",
        "字体": "Font",
        "字号": "Size",
        "字号（8–96）": "Font size (8–96)",
        "宋体": "Songti",
        "导出富文本…": "Export Rich Text…",
        "引用": "Quote",
        "待办事项": "Checklist",
        "快速新建备忘录": "Quick Note",
        "打开随记": "Open SwiftNote",
        "插入": "Insert",
        "插入图片": "Insert Image",
        "插入图片…": "Insert Image…",
        "插入表格": "Insert Table",
        "插入表格…": "Insert Table…",
        "搜索": "Search",
        "搜索备忘录": "Search notes",
        "撤销": "Undo",
        "文件": "File",
        "文字格式": "Text formatting",
        "斜体": "Italic",
        "斜体  ⌘I": "Italic  ⌘I",
        "斜体 ⌘I": "Italic ⌘I",
        "新备忘录": "New Note",
        "新建备忘录": "New Note",
        "新建备忘录  ⌃⌥N": "New Note  ⌃⌥N",
        "新建备忘录  ⌘N": "New Note  ⌘N",
        "无法保存公式。": "Could not save this formula.",
        "无法渲染公式。": "Could not render this formula.",
        "显示": "View",
        "显示或隐藏列表": "Show or hide the note list",
        "显示本地数据": "Show Note Files",
        "显示／隐藏修改时间": "Show/Hide Edit Times",
        "显示／隐藏列表": "Show/Hide Note List",
        "最近修改：": "Last edited: ",
        "标题": "Heading",
        "标题 1": "Heading 1",
        "标题 2": "Heading 2",
        "标题 3": "Heading 3",
        "标题 4": "Heading 4",
        "样式": "Style",
        "格式": "Format",
        "正文": "Text",
        "段落": "Paragraph",
        "独立公式": "Block Math",
        "独立公式源码": "Block math source",
        "空白备忘录": "Empty note",
        "笔记文件缺失，已停止载入，避免覆盖原数据。": "The note file is missing. Loading stopped to protect your data.",
        "第一行为表头，单元格可直接编辑。": "The first row is a header. Click any cell to edit.",
        "粗体": "Bold",
        "粗体  ⌘B": "Bold  ⌘B",
        "粗体 ⌘B": "Bold ⌘B",
        "粘贴": "Paste",
        "系统字体": "System font",
        "编号列表": "Numbered List",
        "编辑": "Edit",
        "苹方": "PingFang",
        "行": "rows",
        "行内公式": "Inline Math",
        "行内公式源码": "Inline math source",
        "行数": "Rows",
        "行数，包含表头": "Rows, including header",
        "表格": "Table",
        "表格内请使用 /math-inline": "Use /math-inline inside a table.",
        "表格单元格内请使用行内公式。": "Use inline math inside table cells.",
        "设置": "Settings",
        "设置…": "Settings…",
        "语言": "Language",
        "请输入公式，最多 8192 字节。": "Enter a formula (up to 8192 bytes).",
        "输入 LaTeX · 回车完成": "Type LaTeX · Return to finish",
        "输入后即刻呈现": "Your formula appears as you type.",
        "退出": "Quit",
        "退出随记": "Quit SwiftNote",
        "重做": "Redo",
        "随手记下，即开即写。\n\n⌘N 新建 · ⌃⌥N 随时快速新建\n# 到 #### 加空格：标题\n**粗体**、*斜体*、`代码`：即时排版\n图片可粘贴、拖入或从工具栏插入；点击图片可调整宽度。": "A thought, a note.\n\n⌘N New note · ⌃⌥N Quick note\n# to #### followed by a space: headings\n**bold**, *italic*, `code`: inline formatting\nPaste or drop images; click an image to resize it.\n/math-inline and /math-block: edit formulas in place.",
        "随记": "SwiftNote",
        "随记 · 点击立即新建  ⌃⌥N\n右键打开菜单": "SwiftNote · Click for a new note  ⌃⌥N\nRight-click for options",
        "隐藏随记": "Hide SwiftNote",
        "项目列表": "Bulleted List",
    ]
}
func L(_ key: String) -> String { Localization.language == .english ? (Localization.english[key] ?? key) : key }
